# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2000 train.py --data VisDrone.yaml --weights yolov5s.pt --cfg models/yolov5s.yaml --epochs 300 --batch-size 8 --img 608 --nosave --device 2,3 --sync-bn >> yolov5s.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2001 train.py --data VisDrone.yaml --weights yolov5l.pt --cfg models/yolov5l.yaml --epochs 300 --batch-size 8 --img 608 --nosave --device 0,3 --sync-bn >> yolov5l.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2002 train.py --data VisDrone.yaml --weights yolov5x.pt --cfg models/yolov5x.yaml --epochs 300 --batch-size 8 --img 608 --nosave --device 0,3 --sync-bn >> yolov5x.out &
# nohup python -m torch.distributed.launch --nproc_per_node 1 --master_port 2002 train.py --data VisDrone.yaml --weights yolov5x.pt --cfg models/yolov5xP2.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 0,3 --sync-bn >> yolov5xP2.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2000 train.py --data VisDrone.yaml --weights yolov5x.pt --cfg models/yolov5xP2CBAM.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 2,3 --sync-bn >> yolov5xP2CBAM.out &
nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2000 train.py --data VisDrone.yaml --weights yolov5x.pt --cfg models/yolov5xTPH.yaml --hyp data/hyps/hyp.visdrone.yaml --epochs 400 --batch-size 4 --img 1536 --nosave --device 0,3 --sync-bn >> yolov5xTPH.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2005 train.py --data VisDrone.yaml --weights yolov5l.pt --cfg models/yolov5lGhost.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 2,3 --sync-bn >> yolov5lGhost_V6.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2005 train.py --data VisDrone.yaml --weights yolov5l.pt --cfg models/yolov5lShffule.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 0,1 --sync-bn >> yolov5lShffule.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2006 train.py --data VisDrone.yaml --weights yolov5l.pt --cfg models/lightModels/yolov5lMobilenetv3Small.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 0,1 --sync-bn >> yolov5lMobilenetv3Small.out &
# nohup python -m torch.distributed.launch --nproc_per_node 2 --master_port 2000 train.py --data VisDrone.yaml --weights yolov5l.pt --cfg models/lightModels/yolov5lEfficientLite.yaml --epochs 300 --batch-size 8 --img 640 --nosave --device 0,2 --sync-bn >> yolov5lEfficientLite.out &